// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// Assethandler is an autogenerated mock type for the Assethandler type
type Assethandler struct {
	mock.Mock
}

// CreateAsset provides a mock function with given fields: c
func (_m *Assethandler) CreateAsset(c *gin.Context) {
	_m.Called(c)
}

// DeleteAsset provides a mock function with given fields: c
func (_m *Assethandler) DeleteAsset(c *gin.Context) {
	_m.Called(c)
}

// DetailAsset provides a mock function with given fields: c
func (_m *Assethandler) DetailAsset(c *gin.Context) {
	_m.Called(c)
}

// ListAssets provides a mock function with given fields: c
func (_m *Assethandler) ListAssets(c *gin.Context) {
	_m.Called(c)
}

// UpdateAsset provides a mock function with given fields: c
func (_m *Assethandler) UpdateAsset(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewAssethandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAssethandler creates a new instance of Assethandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAssethandler(t mockConstructorTestingTNewAssethandler) *Assethandler {
	mock := &Assethandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
